name: Bug Report
description: Report a bug
labels: [bug]
title: 'Bug / '
body:
  - type: textarea
    id: description
    attributes:
      description: 버그에 대해서 설명해주세요.
      label: Bug description
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---

  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: 재현 방법을 자세히 알려주세요. 특정 환경에서만 발생하는 것 같다면, OS와 환경에 대한 정보도 함께 제공해주세요.
      placeholder: |
        최소한으로 재현 가능한 코드 또는 재현 단계를 설명해주세요. 선택 사항이지만 권장됩니다.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---

  - type: textarea
    id: solution
    attributes:
      label: Solution
      placeholder: 어떻게 해결할 수 있을지 설명해주세요.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---

  - type: textarea
    id: etc
    attributes:
      label: 참고자료 등 기타 정보가 있다면 적어주세요.
    validations:
      required: false